### ISSUE TITLE
How to get elasticDump

### ISSUE THREAD

**Issue by xqx1568** [AhmadSakor/falcon#11]
Hi, I want to use falcon to do EL based on Freebase.
Could you tell me how to get the elasticDump in fisrt step?

**Comment by AhmadSakor** [comment]
Hello

thanks for your interest in our work.
currently we don't have the alignments for Freebase.
As a proof of our approach we have DBpedia and also Wikidata (https://github.com/SDM-TIB/falcon2.0)
In order to make Falcon supports Freebase you need to build an index for Freebase where you have the alignments between the labels and the URIs

**Comment by isdhall** [comment]
Hello, 
I understand that we need to build alignments in order to support Freebase or other datasets. However, would you please help me understand how we can build an index where we can have alignments between labels and URIs?

Thank you!
