### ISSUE TITLE
Difference between evaluation.py and evaluation_paper.py?

### ISSUE THREAD

**Issue by rrichajalota** [AhmadSakor/falcon#7]
Hi again @AhmadSakor , could you please explain the difference between evaluation/evaluation.py and evaluation/evaluation_paper.py? There's also an evaluation.py in src/ folder. Which one would you recommend to use? 
As per the paper, for evaluating relation linking, the Frankenstein platform was used. Are these evaluation.py files an adaptation of Frankenstein's evaluation? 
So far, I have been using src/evaluation.py and for both p_enitity and p_relation, I am getting a 0. :/

**Comment by AhmadSakor** [comment]
Hi @rrichajalota 
the difference is the datasets used for the experiments. The evaluation.py and evaluation_paper.py files are only used to read the datasets properly.
In order to evaluate Falcon over the datasets, you should have all the required endpoints (DBpedia, Elasticsearch) ready, then you should modify the endpoints links in the main.py file.
So in order to make the evaluation easier you can use our approach online API. I just uploaded a script "evaluateFalconAPI.py" where you can evaluate the approach via the online API.

**Comment by rrichajalota** [comment]
@AhmadSakor thanks for quickly providing the clarification and the evaluation script. If I choose to run FALCON locally, which function shall I call to fetch the correct entities and relations?  I see the result returned by reRank_relations() in main.py is different than the one returned by the remote Falcon API. 

Shall I change something in the following code snippet from reRank_relations()?
```
mixedRelations=mix_list_items(mixedRelations,k)

    entities=mix_list_items_entities(entities,k)
    mixedRelations.extend(relations_improvement_country(entities))
    
    if nationalityFlag:
        mixedRelations.append(["country","http://dbpedia.org/ontology/country",20])
    
    if oneQuestion:
        print("Relations:")
        print(mixedRelations)
        print("Entities:")
        print(entities)
        return
```

**Comment by AhmadSakor** [comment]
Hi @AhmadSakor 
The function reRand_relations() doesn't produde the final results. It only rank the candidates.
The function evaluate returns the final correct entity and relation.
I don't see that you have to edit the code you mentioned.
Regarding the difference in results between the online API and the code on your machine, there are several configurations to be considered:
- For example, the DBpedia endpoint version (It highly affect the results, because many predicates are changed in each new version of DBpedia which will give different response to the SPARQL queries the approach is executing).
- Another thing to consider is the ElasticSearch version (it may also affect the results because of changes in the matching query of different versions).
- Also some configuration regarding searching and ranking may not be updated in GitHub.
So if you are trying to re-produce the results we reported in the paper or use FALCON as a component in another system, please use the online API because it's the one we used to evaluate FALCON using GERBIL for our paper

**Comment by rrichajalota** [comment]
Hi @AhmadSakor, thank you for this insight. I don't necessarily want to replicate the results. I just want to test FALCON with different DBpedia endpoints and check the recall, precision and F1 scores. In the script that was uploaded yesterday, I want to substitute the call to online API with a function that locally returns entities and relations.
the code for evaluate() in main.py ends with 
```
raw.append([[tup[1],tup[4]] for tup in mixedRelations])        
raw.append([[tup[1],tup[4]] for tup in entities])
return raw
```

Could you please confirm if the online API also returns entities and relations from this raw object?

**Comment by AhmadSakor** [comment]
Hi @rrichajalota 
Yes it should be the same
